[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
todo_dapp = "Cfn4iuNeGA18mo5xMGkiFpPFxiyt88gbtUJtRf2D9nTy"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
